<a href="https://colab.research.google.com/github/MagicPolygon/spotify-data-analysis/blob/main/sampler.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Sampler

To showcase my project on my GitHub repository, I need to showcase my processed dataset. However, the file size is too large to be simply uploaded there. In addition, it consists of over 200,000 rows, and reviewers don't need to see that many. So, I want to instead upload a sample dataset with at most 1000 rows. This notebook will create this.

## Imports and Mounting

To begin, I will import everything I need and mount Google Drive so that I can access the files there:

In [ ]:
import os    # To enable the location of the project to be changed
import pandas as pd

from google.colab import drive    # To enable access to Google Drive files

drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

## Setting up the location to work in
I will now change the current working directory to be the project location:

In [ ]:
project_location = "/content/drive/MyDrive/spotify-data-analysis"
os.chdir(project_location)

## Reading the processed data into a dataframe

Within the CSV file, there is an untitled index. Reading the CSV file normally turns this index into a column titled "Unnamed: 0", and creates a new index. So, I have to register this column as the index of the dataframe by using `index_col="Unnamed: 0"`.

In [ ]:
processed_data_path = "data/processed/processed_spotify_data.csv"
processed_data_df = pd.read_csv(processed_data_path, index_col="Unnamed: 0")

## Viewing the dataframe

In [ ]:
processed_data_df.head()

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,...,month,year_month,hour,day_of_week,day_name,listening_hours,track_play_count,skip_flag,completed_flag,valid_play
0,2017-04-01 17:43:10+00:00,36860,Romance for Cello and Piano,Frederick Delius,Romance for Cello and Piano,spotify:track:70nMUxP46mAcjW5iRpRiyN,clickrow,endplay,False,False,...,4,2017-04,17,5,Saturday,0.010239,1,0,1,True
1,2017-04-01 19:52:27+00:00,36800,"Pavane, Op. 50",Gabriel Fauré,"Fauré: Requiem, Op. 48 / Pavane, Op. 50",spotify:track:2oqgnxjyNYItifLYl9MzaW,clickrow,endplay,False,False,...,4,2017-04,19,5,Saturday,0.010222,1,0,1,True
2,2017-04-01 19:57:07+00:00,280933,Funkin' for Jamaica,Tom Browne,Funkin' For Jamaica,spotify:track:0xbkxTqSaW5blsYgRXpB5I,clickrow,trackdone,False,False,...,4,2017-04,19,5,Saturday,0.078037,1,0,1,True
3,2017-04-01 20:01:58+00:00,290160,Love Rollercoaster,Ohio Players,Honey,spotify:track:1uhUJ5uTuHYdbitv3IsITR,trackdone,trackdone,False,False,...,4,2017-04,20,5,Saturday,0.080600,1,0,1,True
4,2017-04-01 20:09:38+00:00,459533,The Payback,James Brown,The Payback,spotify:track:4u4Kb4W5mWtn9oz4A7SKK6,trackdone,endplay,False,False,...,4,2017-04,20,5,Saturday,0.127648,1,0,1,True

## Randomly sampling the dataframe

Here, I take a random sample of 1000 rows of the full processed date. Then, I make sure the raws are in ascending order of index. Finally, I reset the indices so they run from 0 to 999.

In [ ]:
sample_df = processed_data_df.sample(n=1000, random_state=1)
sample_df = sample_df.sort_index()
sample_df = sample_df.reset_index(drop=True)
sample_df.head(5)

,ts,ms_played,master_metadata_track_name,master_metadata_album_artist_name,master_metadata_album_album_name,spotify_track_uri,reason_start,reason_end,shuffle,skipped,...,month,year_month,hour,day_of_week,day_name,listening_hours,track_play_count,skip_flag,completed_flag,valid_play
0,2017-04-14 14:15:56+00:00,7670,The Price is Wrong,Periphery,Periphery III: Select Difficulty,spotify:track:5P73tP7c5gVzf89awudMFr,clickrow,logout,True,False,...,4,2017-04,14,4,Friday,0.002131,1,0,1,False
1,2017-04-26 11:41:45+00:00,184453,In the Grass,The Flashbulb,Opus at the End of Everything,spotify:track:1rzS1GgROytjhL8FMWupSu,trackdone,trackdone,False,False,...,4,2017-04,11,2,Wednesday,0.051237,1,0,1,True
2,2017-04-28 23:20:28+00:00,203571,Gengar,Dubbacle,Deep Dub Inside 2016,spotify:track:6f214GJFgtrPF1ZO9SSGNb,trackdone,trackdone,False,False,...,4,2017-04,23,4,Friday,0.056548,1,0,1,True
3,2017-05-03 12:31:18+00:00,258000,Feeel,Torus,Feeel,spotify:track:3EVSsbZooWcikVefgz3uC5,trackdone,trackdone,True,False,...,5,2017-05,12,2,Wednesday,0.071667,1,0,1,True
4,2017-10-05 14:36:53+00:00,263828,Psycho Sushi,Eva808,Psycho Sushi,spotify:track:5QtuIc4VSjUp2nniV903bZ,trackdone,trackdone,False,False,...,10,2017-10,14,3,Thursday,0.073286,1,0,1,True

## Writing processed data sample to CSV file

In [ ]:
processed_location = "data/processed/processed_data_sample.csv"
sample_df.to_csv(processed_location, encoding="utf-8")